accounts/urls.py
from django.urls import path
from accounts.views import (
    UserSignupView,
    UserLoginView,
    UserLogoutView,
    UserProfileView,
    UserEditProfileView,
    FollowView,
    UnfollowView,
    FollowerListView,
    FollowingListView,
    PostsView,
    BlockUserView,
    AccountDeactivateView,
    AccountDeleteView
)

app_name = 'accounts'

urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='profile'),
    path('edit-profile/', UserEditProfileView.as_view(), name='edit_profile'),
    path('follow/<str:username>/', FollowView.as_view(), name='follow'),
    path('unfollow/<str:username>/', UnfollowView.as_view(), name='unfollow'),
    path('followers/<int:user_id>/', FollowerListView.as_view(), name='follower_list'),
    path('following/<int:user_id>/', FollowingListView.as_view(), name='following_list'),
    path('posts/', PostsView.as_view(), name='posts'),
    path('block-user/<int:user_id>/', BlockUserView.as_view(), name='block_user'),
    path("deactivate/", AccountDeactivateView.as_view(), name="deactivate"),
    path("delete/", AccountDeleteView.as_view(), name="delete")
]

core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

posts/urls.py
from django.urls import path
from posts.views import (
    CreatePostView,
    PostDetailView,
    LikePostView,
    UnlikePostView,
    CommentPostView,
    ReplyCommentView,
    ReportPostView,
    ReportAccountView,
    PostEditView,
    DeleteCommentView,
    PostDeleteView,
    DislikePostView,
    UndislikePostView
)

app_name = 'posts'

urlpatterns = [
    path('create-post/', CreatePostView.as_view(), name='create_post'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('like/', LikePostView.as_view(), name='like_post'),
    path('unlike/', UnlikePostView.as_view(), name='remove_like'),
    path('dislike/', DislikePostView.as_view(), name='dislike_post'),
    path('undislike/', UndislikePostView.as_view(), name='remove_dislike'),
    path('comment-post/', CommentPostView.as_view(), name='comment_post'),
    path('reply-comment/', ReplyCommentView .as_view(), name='reply_comment'),
    path('report-post/', ReportPostView.as_view(), name='report_post'),
    path('report-account/', ReportAccountView.as_view(), name='report_account'),
    path('edit-post/<post_id>', PostEditView.as_view(), name='edit_post'),
    path('delete-comment/<int:comment_id>/', DeleteCommentView.as_view(), name='delete_comment'),
    path('post/<int:post_id>/delete/', PostDeleteView.as_view(), name='delete_post')

]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
    path('', include('core.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, password=None):

        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            username=username
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None):

        user = self.create_user(
            email,
            password=password,
            username=username
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    username = models.CharField(
        max_length=50,
        unique=True,
        verbose_name="Username",
        help_text="Enter a unique username."
    )
    firstname = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name="First Name",
        help_text="Enter your first name."
    )
    lastname = models.CharField(
        max_length=50,
        blank=True,
        null=True,
        verbose_name="Last Name",
        help_text="Enter your last name."
    )
    bio = models.TextField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name="Bio",
        help_text="Enter a short bio about yourself."
    )
    male = 1
    female = 2
    choice_gender = ((male, "male"), (female, "female"))
    gender = models.IntegerField(
        choices=choice_gender,
        blank=True,
        null=True,
        verbose_name="Gender",
        help_text="Select your gender."
    )
    phonenumber = models.CharField(
        max_length=11,
        blank=True,
        null=True,
        verbose_name="Phone Number",
        help_text="Enter your phone number."
    )
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
        help_text="Provide a valid email address."
    )
    date_of_birth = models.DateField(
        blank=True,
        null=True,
        verbose_name="Date of Birth",
        help_text="Enter your date of birth."
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Active",
        help_text="Designates whether this user account is active."
    )
    is_admin = models.BooleanField(
        default=False,
        verbose_name="Admin",
        help_text="Designates whether this user is an administrator."
    )
    blocked_users = models.ManyToManyField(
        'self',
        symmetrical=False,
        blank=True,
        related_name='blocked_by',
        verbose_name="Blocked Users",
        help_text="Users blocked by this user."
    )
    is_delete = models.BooleanField(
        default=False,
        verbose_name="Deleted",
        help_text="Designates whether this user account is deleted."
    )

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def report_account(self, user, reason):
        Report.objects.create(user=user, account=self, reason=reason)

    @property
    def is_staff(self):
        return self.is_admin

    def block_user(self, user):
        self.blocked_users.add(user)

    def unblock_user(self, user):
        self.blocked_users.remove(user)

    def is_blocked(self, user):
        return self.blocked_users.filter(id=user.id).exists()

    def follower_count(self):
        return self.following_relation.count()

    def following_count(self):
        return self.follower_relation.count()

    def get_followers(self):
        return self.following_relation.all()

    def get_following(self):
        return self.follower_relation.all()

    def post_count(self):
        return self.show_post.count()

    def posts(self):
        return self.show_post.all()

    def delete_account(self):
        self.delete()


class Relationship(models.Model):
    follower = models.ForeignKey(
        MyUser,
        related_name='follower_relation',
        related_query_name='follower_relation',
        on_delete=models.CASCADE,
        verbose_name="Follower"
    )
    following = models.ForeignKey(
        MyUser,
        related_name='following_relation',
        related_query_name='following_relation',
        on_delete=models.CASCADE,
        verbose_name="Following"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created at"
    )

    def __str__(self):
        return f'{self.follower.username} -> {self.following.username}'


class Report(models.Model):
    user = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name="reporter_user"
    )
    account = models.ForeignKey(
        MyUser,
        on_delete=models.CASCADE,
        related_name='reported_accounts',
        blank=True,
        null=True
    )
    reason = models.TextField(
        max_length=500
    )

    def __str__(self):
        if self.account:
            return f"Report on account: {self.account.username}"
        else:
            return "Invalid report"

accounts/forms.py
from django import forms
from accounts.models import MyUser


class UserSignupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ['email', 'username', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password and confirm_password and password != confirm_password:
            raise forms.ValidationError("Passwords do not match.")

        return cleaned_data


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserEditProfileForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "username"}
        )
    )
    firstname = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "firstname"}
            )
    )
    lastname = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "lastname"}
            )
    )
    bio = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={"placeholder": "bio"},
            )
    )
    gender_choices = (
        (1, 'Male'),
        (2, 'Female'),
    )
    gender = forms.ChoiceField(
        choices=gender_choices,
        widget=forms.Select(
            attrs={"placeholder": "gender"}
            )
    )
    phonenumber = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "phonenumber"}
            )
    )
    date_of_birth = forms.DateField(
        required=False,
        widget=forms.TextInput(
            attrs={"placeholder": "date_of_birth"}
            )
    )

    class Meta:
        model = MyUser
        fields = [
            'username', 'firstname', 'lastname',
            'bio', 'gender',
            'phonenumber', 'date_of_birth'
            ]

    def clean_phonenumber(self):
        phonenumber = self.cleaned_data.get('phonenumber')
        if not phonenumber.isnumeric():
            raise forms.ValidationError("Invalid phone number.")
        return phonenumber

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from accounts.models import MyUser, Relationship
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from posts.models import PostModel
from django.http import HttpResponse
from accounts.forms import UserLoginForm, UserSignupForm, UserEditProfileForm
from django.views.generic import View, TemplateView


class UserSignupView(View):
    def get(self, request):
        form = UserSignupForm()
        return render(request, 'accounts/signup.html', {'form': form})

    def post(self, request):
        form = UserSignupForm(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('accounts:login')

        return render(request, 'accounts/signup.html', {'form': form})


class UserLoginView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = UserLoginForm(request.POST)

        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(request, email=email, password=password)

            if user is not None:
                login(request, user)
                messages.success(request, "Logged in successfully.")
                return redirect('accounts:profile', request.user.id)

        messages.error(request, "Invalid email or password.")
        return render(request, 'accounts/login.html', {'form': form})


class UserLogoutView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            messages.info(request, "Please log in first.")
            return redirect('accounts:login')

        logout(request)
        messages.success(request, "Logged out successfully.")
        return redirect('accounts:login')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(MyUser, pk=user_id)
        query = request.GET.get('q')
        if query:
            results = MyUser.objects.filter(username__icontains=query)
        else:
            results = None
        post = PostModel.objects.filter(user=user)
        context = {'user': user, 'post': post, 'results': results}
        return render(request, 'accounts/profile.html', context=context)


class UserEditProfileView(LoginRequiredMixin, View):
    def get(self, request):
        form = UserEditProfileForm(instance=request.user)
        return render(request, 'accounts/edit_profile.html', {'form': form})

    def post(self, request):
        form = UserEditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('accounts:profile', request.user.id)
        else:
            messages.error(request, "Error updating profile.")
            return render(
                request, 'accounts/edit_profile.html', {'form': form}
                )


class FollowView(LoginRequiredMixin, View):
    def get(self, request, username):
        user_to_follow = get_object_or_404(MyUser, username=username)
        if Relationship.objects.filter(
                follower=request.user, following=user_to_follow).exists():

            messages.info(
                request,
                f"You are already following {user_to_follow.username}."
                )
        else:
            Relationship.objects.create(
                follower=request.user,
                following=user_to_follow
                )
            messages.success(
                request, f"You are now following {user_to_follow.username}."
                )

        return redirect('accounts:profile', user_to_follow.id)


class UnfollowView(LoginRequiredMixin, View):
    def get(self, request, username):
        user_to_unfollow = get_object_or_404(MyUser, username=username)
        Relationship.objects.filter(
            follower=request.user,
            following=user_to_unfollow
        ).delete()
        messages.success(
            request, f"You have unfollowed {user_to_unfollow.username}."
            )
        return redirect('accounts:profile', user_to_unfollow.id)


class FollowerListView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(MyUser, pk=user_id)
        followers = user.get_followers()
        context = {
            'user': user,
            'followers': followers
        }
        return render(request, 'accounts/follower_list.html', context)


class FollowingListView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(MyUser, pk=user_id)
        following = user.get_following()
        context = {
            'user': user,
            'following': following
        }
        return render(request, 'accounts/following_list.html', context)


class PostsView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = PostModel.objects.filter(user=self.request.user)
        return context


class BlockUserView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = request.user
        blocked_user = get_object_or_404(MyUser, id=user_id)

        if user.is_authenticated and user != blocked_user:
            if not user.is_blocked(blocked_user):
                user.block_user(blocked_user)
                return HttpResponse("User blocked successfully.")
            else:
                return HttpResponse("User is already blocked.")

        return HttpResponse("Invalid request.")


class AccountDeleteView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        user.delete_account()
        messages.success(request, "Your account has been deleted.")
        return redirect("accounts:login")


class AccountDeactivateView(LoginRequiredMixin, View):
    def get(self, request):
        user = request.user
        user.is_active = False
        user.save()
        messages.success(request, "Your account has been deactivated.")
        return redirect("accounts:login")

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/edit_profile.css' %}">
<div class="container">
    <br>
    <br>
        <div class="row" id="main">
            <div class="col-md-4 well" id="leftPanel">
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <img src="http://lorempixel.com/200/200/abstract/1/" alt="Texto Alternativo" class="img-circle img-thumbnail">
                            <p>Edit</p>
                            <div class="btn-group">
                                <button type="button" class="btn btn-warning">
                                    Social</button>
                                <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                                    <span class="caret"></span><span class="sr-only">Social</span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="#">Twitter</a></li>
                                    <li><a href="https://plus.google.com/+Jquery2dotnet/posts">Google +</a></li>
                                    <li><a href="https://www.facebook.com/jquery2dotnet">Facebook</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Github</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8 well" id="rightPanel">
                <div class="row">
        <div class="col-md-12">
            <form action="" method="POST">
                {% csrf_token %}
                <h2>Edit your profile.<small>It's always easy</small></h2>
                <hr class="colorgraph">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.username}}
                        </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.firstname}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.lastname}}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    {{form.bio}}
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.gender}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.phonenumber}}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6">
                        <div class="form-group">
                            {{form.date_of_birth}}
                        </div>
                    </div>
                </div>
                <hr class="colorgraph">
                <div class="row">
                    <div class="col-xs-12 col-md-6"></div>
                </div>
                <input type="submit" value="Save"><a href="{% url "accounts:profile" request.user.id %}" ><button class="btn btn-primary">Back</button></a>
                
            </form>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h2 class="panel-title">Deactivate Account</h2>
                            </div>
                            <div class="panel-body">
                                <p>Are you sure you want to deactivate your account?</p>
                                <form method="POST" action="{% url 'accounts:deactivate' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Deactivate Account</button>
                                    <a href="{% url 'accounts:profile' request.user.id %}" class="btn btn-default">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h2 class="panel-title">Delete Account</h2>
                            </div>
                            <div class="panel-body">
                                <p>Are you sure you want to delete your account? This action cannot be undone.</p>
                                <form method="POST" action="{% url 'accounts:delete' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete Account</button>
                                    <a href="{% url 'accounts:profile' request.user.id %}" class="btn btn-default">Cancel</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="t_and_c_m" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="myModalLabel">Terms & Conditions</h4>
                </div>
                <div class="modal-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Similique, itaque, modi, aliquam nostrum at sapiente consequuntur natus odio reiciendis perferendis rem nisi tempore possimus ipsa porro delectus quidem dolorem ad.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">I Agree</button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    </div>
            </div>
         </div>       
    </div>

{% endblock content %}    

accounts/templates/accounts/follower_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Followers of {{ user.username }}</h1>
  <ul>
    {% for follower_user in followers %}
      <a href="{% url 'accounts:profile' follower_user.follower.id %}"><li>{{ follower_user.follower.username }}</li></a>
    {% empty %}
      <li>No followers yet.</li>
    {% endfor %}
    <a href="{% url "accounts:profile" request.user.id %}" ><button class="btn btn-primary">Back</button></a>
  </ul>
{% endblock %}

accounts/templates/accounts/following_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Following of {{ user.username }}</h1>
  <ul>
    {% for following_user in following %}
      <a href="{% url 'accounts:profile' following_user.following.id %}"><li>{{ following_user.following.username }}</li></a>
    {% empty %}
      <li>Not following anyone yet.</li>
    {% endfor %}
    <a href="{% url "accounts:profile" request.user.id %}" ><button class="btn btn-primary">Back</button></a>
  </ul>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<script src="{% static 'js/profile.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

<header>
	<div class="container">
		<div class="profile">
			<div class="profile-image">
				<img src="https://images.unsplash.com/photo-1513721032312-6a18a42c8763?w=152&h=152&fit=crop&crop=faces" alt="">
			</div>
			<div class="profile-user-settings">
				<h1 class="profile-user-name" style="color: purple; font-size: 35px;">{{user.username}}</h1>
				{% if request.user == user %}
				<a href='{% url "accounts:edit_profile" %}'>
					<button class="btn profile-edit-btn">Edit Profile</button>
				</a>
				<a href='{% url "posts:create_post" %}'>
					<button class="btn profile-edit-btn">Create Post</button>
				</a>
				{% endif %}
				<button class="btn profile-settings-btn" aria-label="profile settings">
					<i class="fas fa-cog" aria-hidden="true"></i>
				</button>
			</div>
			<div class="profile-stats">
				<ul>
					<li><span class="profile-stat-count">{{ user.post_count }}</span> posts</li>
					<a href="{% url 'accounts:follower_list' user.id %}">
						<li><span class="profile-stat-count">{{ user.follower_count }}</span> followers</li>
					</a>
					<a href="{% url 'accounts:following_list' user.id %}">
						<li><span class="profile-stat-count"> {{ user.following_count }}</span> following</li>
					</a>
					
				</ul>
			</div>
			{% if request.user != user %}
			{% if request.user in user.followers.all %}
			<form action="{% url 'accounts:follow' user.username %}" method="get" class="follow-form">
				{% csrf_token %}
				<button type="submit" class="btn profile-edit-btn">Follow</button>
			</form>
			{% else %}
			<form action="{% url 'accounts:unfollow' user.username %}" method="get" class="follow-form">
				{% csrf_token %}
				<button type="submit" class="btn profile-edit-btn">Unfollow</button>
			</form>
			{% endif %}
			{% endif %}
			<div class="profile-bio">
				<p><span class="profile-real-name">{{user.bio}}</span></p>
			</div>
		</div>
		<!-- End of profile section -->
	</div>
	<!-- End of container -->
</header>

<main>
	<div class="container">
		<div id="loader" class="loader"></div>
		<div id="post-container">
			{% for post in user.posts %}
				{% for image in post.images.all %}
					<a href="{% url 'posts:post_detail' post.slug %}"><img style="height: 100px; width: auto;" src="{{ image.image.url}}" alt="{{image.alt}}"></a>
				{% endfor %}
			{% endfor %}
		</div>
	</div>
	<!-- End of container -->
</main>

<script>
	// Hide the loader and show the posts
	window.addEventListener('load', function () {
		var loader = document.getElementById('loader');
		var postContainer = document.getElementById('post-container');
		
		loader.style.display = 'none';
		postContainer.style.display = 'block';
	});

	// Hide the loader after posting a new post
	function hideLoader() {
		var loader = document.getElementById('loader');
		loader.style.display = 'none';
	}

	// Example function to simulate posting a new post
	function addNewPost() {
		// Simulating a delay to mimic the time it takes to post a new post
		setTimeout(function () {
			// Code to add the new post

			// After the new post is added, hide the loader
			hideLoader();
		}, 2000);
	}
</script>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form>

{% endblock content %}