accounts/urls.py
from django.urls import path
from accounts.views import (
    UserSignupView,
    UserLoginView,
    UserLogoutView,
    UserProfileView,
    UserEditProfileView,
    FollowView,
    UnfollowView,
    FollowerListView,
    FollowingListView,
    PostsView,
    BlockUserView,
    AccountDeactivateView,
    AccountDeleteView
)

app_name = 'accounts'

urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', UserProfileView.as_view(), name='profile'),
    path('edit-profile/', UserEditProfileView.as_view(), name='edit_profile'),
    path('follow/<str:username>/', FollowView.as_view(), name='follow'),
    path('unfollow/<str:username>/', UnfollowView.as_view(), name='unfollow'),
    path('followers/<int:user_id>/', FollowerListView.as_view(), name='follower_list'),
    path('following/<int:user_id>/', FollowingListView.as_view(), name='following_list'),
    path('posts/', PostsView.as_view(), name='posts'),
    path('block-user/<int:user_id>/', BlockUserView.as_view(), name='block_user'),
    path("deactivate/", AccountDeactivateView.as_view(), name="deactivate"),
    path("delete/", AccountDeleteView.as_view(), name="delete")
]

core/urls.py
from django.urls import path
from .views import HomeView

app_name = "core"
urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

posts/urls.py
from django.urls import path
from posts.views import (
    CreatePostView,
    PostDetailView,
    LikePostView,
    UnlikePostView,
    CommentPostView,
    ReplyCommentView,
    ReportPostView,
    ReportAccountView,
    PostEditView,
    DeleteCommentView,
    PostDeleteView,
    DislikePostView,
    UndislikePostView
)

app_name = 'posts'

urlpatterns = [
    path('create-post/', CreatePostView.as_view(), name='create_post'),
    path('post/<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('like/', LikePostView.as_view(), name='like_post'),
    path('unlike/', UnlikePostView.as_view(), name='remove_like'),
    path('dislike/', DislikePostView.as_view(), name='dislike_post'),
    path('undislike/', UndislikePostView.as_view(), name='remove_dislike'),
    path('comment-post/', CommentPostView.as_view(), name='comment_post'),
    path('reply-comment/', ReplyCommentView .as_view(), name='reply_comment'),
    path('report-post/', ReportPostView.as_view(), name='report_post'),
    path('report-account/', ReportAccountView.as_view(), name='report_account'),
    path('edit-post/<post_id>', PostEditView.as_view(), name='edit_post'),
    path('delete-comment/<int:comment_id>/', DeleteCommentView.as_view(), name='delete_comment'),
    path('post/<int:post_id>/delete/', PostDeleteView.as_view(), name='delete_post')

]

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('posts.urls')),
    path('', include('core.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

posts/forms.py
from django import forms
from .models import PostModel, Comment


class CreatePostForm(forms.ModelForm):
    caption = forms.CharField(
        widget=forms.Textarea,
        max_length=500,
        required=True
        )
    location = forms.CharField(
        max_length=50,
        required=False
        )
    image = forms.ImageField(
        required=True
        )

    class Meta:
        model = PostModel
        fields = ['caption', 'location', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']
        widgets = {
            'comment_text': forms.TextInput(attrs={'maxlength': 128}),
        }


class ReplyForm(forms.Form):
    reply_text = forms.CharField(max_length=128)


class ReportForm(forms.Form):
    reason = forms.CharField(
        widget=forms.Textarea,
        max_length=500
        )


class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = ['caption', 'location']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from .models import PostModel, Comment, Report, SendPost, Image, Like
from accounts.models import MyUser
from django.contrib.auth.decorators import login_required
from django.views import View
from .forms import CreatePostForm, CommentForm, ReplyForm, ReportForm, PostForm
from django.utils.text import slugify
from django.utils.decorators import method_decorator


class CreatePostView(View):
    def get(self, request):
        form = CreatePostForm()
        return render(request, 'posts/create_post.html', {'form': form})

    def post(self, request):
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            user_id = request.user.id
            caption = form.cleaned_data['caption']
            slug = slugify(form.cleaned_data['caption'][:20])
            location = form.cleaned_data['location']
            image = form.cleaned_data['image']
            user = MyUser.objects.get(id=user_id)
            post = PostModel(
                user=user,
                caption=caption,
                slug=slug,
                location=location
            )
            post.save()

            Image.objects.create(
                name=image.name,
                alt="",
                image=image,
                post=post
            )

            return redirect('accounts:profile', request.user.id)
        return render(request, 'posts/create_post.html', {'form': form})


class PostDetailView(View):
    def get(self, request, slug):
        posts = PostModel.objects.filter(slug=slug)
        if posts.exists():
            post = posts.first()
            comments = Comment.objects.filter(post=post, parent=None)
            is_like = Like.is_like(post, request.user)
            return render(
                request,
                'posts/post_detail.html',
                {'post': post, 'comments': comments, 'is_like': is_like}
            )
        else:
            return HttpResponse("Post not found")

    def post(self, request, slug):
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data['comment_text']
            posts = PostModel.objects.filter(slug=slug)
            if posts.exists():
                post = posts.first()
                Comment.objects.create(
                    comment_text=comment_text,
                    user=request.user,
                    post=post
                )
                return redirect("posts:post_detail", post.slug)
        return redirect("posts:post_detail", slug)


class LikePostView(View):
    @method_decorator(require_POST)
    def post(self, request):
        post_id = request.POST.get('post_id')
        post = PostModel.objects.get(id=post_id)
        post.like_post(request.user)
        return redirect("posts:post_detail", post.slug)


class UnlikePostView(View):
    @method_decorator(require_POST)
    def post(self, request):
        post_id = request.POST.get('post_id')
        post = PostModel.objects.get(id=post_id)
        post.remove_like(request.user)
        return redirect("posts:post_detail", post.slug)


class DislikePostView(View):
    @method_decorator(require_POST)
    def post(self, request):
        post_id = request.POST.get('post_id')
        post = PostModel.objects.get(id=post_id)
        post.dislike_post(request.user)
        return redirect("posts:post_detail", post.slug)


class UndislikePostView(View):
    @method_decorator(require_POST)
    def post(self, request):
        post_id = request.POST.get('post_id')
        post = PostModel.objects.get(id=post_id)
        post.remove_dislike(request.user)
        return redirect("posts:post_detail", post.slug)


class CommentPostView(View):
    @require_POST
    def post(self, request):
        post_id = request.POST.get('post_id')
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = form.cleaned_data['comment_text']
            post = get_object_or_404(PostModel, id=post_id)
            Comment.objects.create(
                comment_text=comment_text,
                user=request.user,
                post=post)
            return HttpResponse({'message': 'Comment added successfully'})
        return HttpResponse({'message': 'Invalid form data'})


class ReplyCommentView(View):
    @method_decorator(require_POST)
    def post(self, request):
        comment_id = request.POST.get('comment_id')
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply_text = form.cleaned_data['reply_text']
            comment = get_object_or_404(Comment, id=comment_id)
            Comment.objects.create(
                comment_text=reply_text,
                user=request.user,
                post=comment.post,
                reply_to=comment
            )
            return redirect("posts:post_detail", comment.post.slug)
        return HttpResponse({'message': 'Invalid form data'})


class ReportPostView(View):
    @require_POST
    def post(self, request):
        post_id = request.POST.get('post_id')
        form = ReportForm(request.POST)
        if form.is_valid():
            reason = form.cleaned_data['reason']
            post = get_object_or_404(PostModel, id=post_id)
            Report.objects.create(user=request.user, post=post, reason=reason)
            return HttpResponse({'message': 'Post reported successfully'})
        return HttpResponse({'message': 'Invalid form data'})


class ReportAccountView(View):
    @require_POST
    def post(self, request):
        account_id = request.POST.get('account_id')
        form = ReportForm(request.POST)
        if form.is_valid():
            reason = form.cleaned_data['reason']
            account = get_object_or_404(MyUser, id=account_id)
            Report.objects.create(
                user=request.user,
                account=account,
                reason=reason
                )
            return redirect("posts:post_detail", request.user.id)
        return redirect("posts:post_detail", request.user.id)


class SendPostView(View):
    @login_required
    def get(self, request, post_id, recipient_id):
        post = get_object_or_404(PostModel, id=post_id)
        recipient = get_object_or_404(MyUser, id=recipient_id)
        sent_post = SendPost(
            sender=request.user,
            recipient=recipient,
            post=post)
        sent_post.save()
        return HttpResponse("Post sent successfully!")


class PostEditView(View):
    def get(self, request, post_id):
        post = get_object_or_404(PostModel, id=post_id, user=request.user)
        form = PostForm(instance=post)
        return render(
            request,
            'posts/edit_post.html',
            {'form': form, 'post': post}
            )

    def post(self, request, post_id):
        post = get_object_or_404(PostModel, id=post_id, user=request.user)
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post.slug)
        return render(
            request,
            'posts/edit_post.html',
            {'form': form, 'post': post}
            )


class PostDeleteView(View):
    def get(self, request, post_id):
        post = get_object_or_404(PostModel, id=post_id, user=request.user)
        return render(request, 'delete_post.html', {'post': post})

    def post(self, request, post_id):
        post = get_object_or_404(PostModel, id=post_id, user=request.user)
        post.delete()
        return redirect('accounts:profile', request.user.id)


class DeleteCommentView(View):
    def post(self, request, comment_id):
        comment = get_object_or_404(Comment, id=comment_id)
        if comment.user == request.user:
            comment.delete()
        return redirect("posts:post_detail", slug=comment.post.slug)

posts/templates/posts/create_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Post</title>
</head>
<body>
    <h1>Create Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
    <a href="{% url "accounts:profile" request.user.id %}" ><button class="btn btn-primary">Back</button></a>
</body>
</html>

posts/templates/posts/delete_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Post</title>
</head>
<body>
    <h1>Delete Post</h1>
    <p>Are you sure you want to delete the post "{{ post.slug }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
</body>
</html>

posts/templates/posts/edit_post.html
<!DOCTYPE html>
<html>
<head>
    <title>Edit Post</title>
</head>
<body>
    <h1>Edit Post</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>Post Detail</title>
</head>
<body>
    
    <h1>Post Detail</h1>
        <form action="{% url 'posts:like_post' %}" method="post" id="like-post-form">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit">Like</button>
        </form>
        <form action="{% url 'posts:remove_like' %}" method="post" id="unlike-post-form" style="display: none;">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit">Unlike</button>
        </form>
        <form action="{% url 'posts:dislike_post' %}" method="post" id="dislike-post-form">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit">Dislike</button>
        </form>
        <form action="{% url 'posts:remove_dislike' %}" method="post" id="remove-dislike-post-form" style="display: none;">
            {% csrf_token %}
            <input type="hidden" name="post_id" value="{{ post.id }}">
            <button type="submit">Remove Dislike</button>
        </form>
    <p>Like count: <span id="like-count">{{ post.likes.count }}</span></p>
    <p>Dislike count: <span id="dislike-count">{{ post.dislikes.count }}</span></p>
    {% if request.user == post.user %}
        <a href="{% url 'posts:edit_post' post.id %}" class="btn btn-primary">Edit</a>
        <form action="{% url 'posts:delete_post' post.id %}" method="post">
            {% csrf_token %}
            <button type="submit">Delete</button>
        </form>
    {% endif %}
    
    <h2>{{ post.slug }}</h2>
    <p>{{ post.caption }}</p>
    <p>Created At: {{ post.create_time }}</p>
    <p>Last Updated At: {{ post.update_time }}</p>
    <p>Location: {{ post.location }}</p>

    <h3>Comments</h3>
    <ul>
        {% for comment in comments %}
        <li>
            <p>{{ comment.comment_text }}</p>
            <p>Commented by: {{ comment.user }}</p>
            <p>Created At: {{ comment.create_time }}</p>
            {% if comment.child.count > 0 %}
            <ul>
                {% for reply in comment.child.all %}
                <li>
                    <p>{{ reply.comment_text }}</p>
                    <p>Replied by: {{ reply.user }}</p>
                    <p>Created At: {{ reply.create_time }}</p>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <form action="{% url 'posts:reply_comment' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="comment_id" value="{{ comment.id }}">
                <input type="text" name="reply_text" placeholder="Reply to this comment">
                <input type="submit" value="Reply">
            </form>
            {% if request.user == comment.user %}
                 <form action="{% url 'posts:delete_comment' comment.id %}" method="post" class="delete-comment-form">
                {% csrf_token %}
                <button type="submit">Delete Comment</button>
                </form>
            {% endif %}
            
        </li>
        {% endfor %}
    </ul>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" name="comment_text" placeholder=" comment">
        <input type="submit" value="send">
    </form>
    <a href="{% url "accounts:profile" request.user.id %}" ><button class="btn btn-primary">Back</button></a>

    <script>
        // Update like and dislike counts when the forms are submitted
        document.getElementById("like-post-form").addEventListener("submit", function(event) {
            event.preventDefault();
            // Check if the dislike form is visible
            var dislikeForm = document.getElementById("dislike-post-form");
            if (dislikeForm.style.display !== "none") {
                // Increment the like count
                var likeCount = document.getElementById("like-count");
                likeCount.innerText = parseInt(likeCount.innerText) + 1;
                // Hide the "Like" button and show the "Unlike" button
                document.getElementById("like-post-form").style.display = "none";
                document.getElementById("unlike-post-form").style.display = "block";
            }
        });

        document.getElementById("unlike-post-form").addEventListener("submit", function(event) {
            event.preventDefault();
            // Decrement the like count
            var likeCount = document.getElementById("like-count");
            likeCount.innerText = parseInt(likeCount.innerText) - 1;
            // Hide the "Unlike" button and show the "Like" button
            document.getElementById("unlike-post-form").style.display = "none";
            document.getElementById("like-post-form").style.display = "block";
        });

        document.getElementById("dislike-post-form").addEventListener("submit", function(event) {
            event.preventDefault();
            // Check if the like form is visible
            var likeForm = document.getElementById("like-post-form");
            if (likeForm.style.display !== "none") {
                // Increment the dislike count
                var dislikeCount = document.getElementById("dislike-count");
                dislikeCount.innerText = parseInt(dislikeCount.innerText) + 1;
                // Hide the "Dislike" button and show the "Remove Dislike" button
                document.getElementById("dislike-post-form").style.display = "none";
                document.getElementById("remove-dislike-post-form").style.display = "block";
            }
        });

        document.getElementById("remove-dislike-post-form").addEventListener("submit", function(event) {
            event.preventDefault();
            // Decrement the dislike count
            var dislikeCount = document.getElementById("dislike-count");
            dislikeCount.innerText = parseInt(dislikeCount.innerText) - 1;
            // Hide the "Remove Dislike" button and show the "Dislike" button
            document.getElementById("remove-dislike-post-form").style.display = "none";
            document.getElementById("dislike-post-form").style.display = "block";
        });
    </script>
</body>
</html>